apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: $DEFAULT_USER
  labels:
    strimzi.io/cluster: $CLUSTER
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: $TOPIC_NAME
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: $TOPIC_NAME
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: $TOPIC_NAME
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: $TOPIC_NAME
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: $TOPIC_NAME
          patternType: literal
        operation: Describe
        host: "*"